# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20160611_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover',
        ),
        migrations.AddField(
            model_name='media',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='books'),
        ),
        migrations.AddField(
            model_name='media',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
